export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const SEND_MONEY_SUCCESS = "SEND_MONEY_SUCCESS";
export const FETCH_INV_SUCCESS = "FETCH_INV_SUCCESS";

export const DB_CHANGED = "DB_CHANGED";
export const WITHDRAW_MONEY_SUCCESS = "WITHDRAW_MONEY_SUCCESS";
